### ISSUE TITLE
Sandbox request authorization problem

### ISSUE THREAD

**Issue by z3phyro** [stevenmaguire/uber-php#10]
When I enter this...
    $client = new Client(array(
                'access_token' => env('ZORAN_ACCESS_TOKEN'),
                'server_token' => env('UBER_SERVER_TOKEN'),
                'use_sandbox'  => true, // optional, default false
                'version'      => 'v1', // optional, default 'v1'
                'locale'       => 'en_UK', // optional, default 'en_US'
            ));

```
        $request = $client->requestRide(array(
                'start_latitude' => '41.85582993',
                'start_longitude' => '-87.62730337',
                'end_latitude' => '41.87499492',
                'end_longitude' => '-87.67126465'
            ));
```

 I get the following answer 

{#214 ▼
  +"message": "Requires at least one scope. Available scopes: "
  +"code": "unauthorized"
}

I haven't enabled yet the posibility to make real request but this shouldn't be the problem isn't it?

Thanks in advance

**Comment by stevenmaguire** [comment]
It is my understanding that the sandbox will function exactly as in production. I'd suggest contacting their support to confirm this information.

**Comment by z3phyro** [comment]
The problem occurs when you try to put more than one scope... at least when using sandbox... i just putted one and it worked thx. :)
