### ISSUE TITLE
Class 'Stevenmaguire\Uber\Client' not found

### ISSUE THREAD

**Issue by ivishal3258** [stevenmaguire/uber-php#13]
I am using this on PHP 5.6 but i am getting the error mention in subject. Can anyone tell me the step by step integration as given for Node.js for uber, that would be helpful for me .

**Comment by stevenmaguire** [comment]
Are you attempting to use this package in a node.js project?

**Comment by ivishal3258** [comment]
I have using uber client php and for this first i have installed " composer require stevenmaguire/oauth2-uber " file through composer then i have written the code as provided there for  "Authorization Code Flow "and then when i trying to run this code i am getting this error

**Comment by ivishal3258** [comment]
Please have  look into this code which i have added in my file:-
-------------------------------------------------------------------------
```php
<?php

  $provider = new Stevenmaguire\OAuth2\Client\Provider\Uber([
    'clientId'          => '{uber-client-id}',
    'clientSecret'      => '{uber-client-secret}',
    'redirectUri'       => 'https://example.com/callback-url'
]);

if (!isset($_GET['code'])) {

    // If we don't have an authorization code then get one
    $authUrl = $provider->getAuthorizationUrl();
    $_SESSION['oauth2state'] = $provider->getState();
    header('Location: '.$authUrl);
    exit;

// Check given state against previously stored one to mitigate CSRF attack
} elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {

    unset($_SESSION['oauth2state']);
    exit('Invalid state');

} else {

    // Try to get an access token (using the authorization code grant)
    $token = $provider->getAccessToken('authorization_code', [
        'code' => $_GET['code']
    ]);

    // Optional: Now you have a token you can look up a users profile data
    try {

        // We got an access token, let's now get the user's details
        $user = $provider->getResourceOwner($token);

        // Use these details to create a new profile
        printf('Hello %s!', $user->getFirstname());

    } catch (Exception $e) {

        // Failed to get user details
        exit('Oh dear...');
    }

    // Use this to interact with an API on the users behalf
    echo $token->getToken();
}

$options = [
    'state' => 'OPTIONAL_CUSTOM_CONFIGURED_STATE',
    'scope' => ['profile','history_lite'] // array or string
];

$authorizationUrl = $provider->getAuthorizationUrl($options);

?>
```
--------------------------------------

Do i need to add any extra file or code..?

**Comment by stevenmaguire** [comment]
The code you have provided is for the `oauth2-uber` package, not the `uber-php` package, which is this one, where you've logged the issue.

You should also run `composer require stevenmaguire/uber-php`.

**Comment by ivishal3258** [comment]
Yes correct and even first i have to authenticate the user from uber so thats why i am doing this.

Do i need to run both for authenticating the user first ...?
-------

composer require stevenmaguire/uber-php
composer require stevenmaguire/oauth2-uber

**Comment by ivishal3258** [comment]
I have run both files but couldn't be able to install both files getting error. I have attached an error file. Please find that.
![problem](https://cloud.githubusercontent.com/assets/8208726/20894823/edf4d788-bb3c-11e6-8e4f-bd8980fcbe8a.png)

**Comment by ivishal3258** [comment]
Hello Steven 

I am waiting for your response.

**Comment by stevenmaguire** [comment]
Can you share your composer.json file of your project?

`oauth2-php` and `uber-php` require `"guzzlehttp/guzzle": "~6.0"` which is in direct conflict with `"guzzlehttp/guzzle": "5.3.1"`.

**Comment by ivishal3258** [comment]
Here is my composer.json file.
--------------------------

{
    "require": {
        "league/oauth2-client": "^1.4",
        "stevenmaguire/oauth2-uber": "^0.2.1"
    }
}

**Comment by stevenmaguire** [comment]
You don't need to require 'league/oauth2-client', it is included with 'stevenmaguire/oauth2-uber'.
