### ISSUE TITLE
Invalid OAuth 2.0 credentials provided.

### ISSUE THREAD

**Issue by neutronixx** [stevenmaguire/uber-php#14]
Hi, I have this code:

```
$client = new Stevenmaguire\Uber\Client(array(
    'access_token' => 'kY6GFCWP9cyQ_-h-_haFKUH6gDxz34NOJ',//(Client ID)
    'server_token' => 'cxt-4SJSXDEvcxsAQ342vsCC08-ehTvFs3Kv_TC0cJ',//(Server Token)
    'use_sandbox'  => true, // optional, default false
    'version'      => 'v1.2', // optional, default 'v1.2'
    //'locale'       => 'en_US', // optional, default 'en_US'
    'locale'       => 'es_MX', // optional, default 'en_US'
));

$profile = $client->getProfile();
print_r($profile);
```

And this result: 

> Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://sandbox-api.uber.com/v1.2/me` resulted in a `401 Unauthorized` response: {"message":"Invalid OAuth 2.0 credentials provided.","code":"unauthorized"} ' in /home/

What could be wrong? Your help would be appreciated

**Comment by stevenmaguire** [comment]
`access_token` is for the access token you've acquired on behalf of a given user. Not the Client ID provided by Uber's App platform. Is this value `kY6GFCWP9cyQ_-h-_haFKUH6gDxz34NOJ` an access token or a client id?

**Comment by neutronixx** [comment]
Thanks, I see that I need another library (oauth2-uber)
