### ISSUE TITLE
message: We have experienced a problem, code:internal_server_error

### ISSUE THREAD

**Issue by neutronixx** [stevenmaguire/uber-php#15]
Do you know why allway I get this response from any request?

> [1] => GuzzleHttp\Psr7\Response Object
>                                 (
>                                     [reasonPhrase:GuzzleHttp\Psr7\Response:private] => Internal Server Error
>                                     [statusCode:GuzzleHttp\Psr7\Response:private] => 500
>                                     [headers:GuzzleHttp\Psr7\Response:private] => Array
>                                         (
>                                             [Server] => Array
>                                                 (
>                                                     [0] => nginx
>                                                 )
> 
>                                             [Date] => Array
>                                                 (
>                                                     [0] => Thu, 26 Jan 2017 02:32:34 GMT
>                                                 )
> 
>                                             [Content-Type] => Array
>                                                 (
>                                                     [0] => application/json
>                                                 )
> 
>                                             [Content-Length] => Array
>                                                 (
>                                                     [0] => 75
>                                                 )
> 
>                                             [Connection] => Array
>                                                 (
>                                                     [0] => keep-alive
>                                                 )
> 
>                                             [X-Uber-App] => Array
>                                                 (
>                                                     [0] => uberex-sandbox
>                                                     [1] => migrator-uberex-sandbox-optimus
>                                                 )
> 
>                                             [Strict-Transport-Security] => Array
>                                                 (
>                                                     [0] => max-age=604800
>                                                 )
> 
>                                             [X-Content-Type-Options] => Array
>                                                 (
>                                                     [0] => nosniff
>                                                 )
> 
>                                             [X-XSS-Protection] => Array
>                                                 (
>                                                     [0] => 1; mode=block
>                                                 )
> 
>                                         )
> 
> [message:protected] => Server error: `GET https://sandbox-api.uber.com/v1.2/history?limit=50&offset=0` resulted in a `500 Internal Server Error` response:
> {"message":"We have experienced a problem.","code":"internal_server_error"}...

My code is:

```
$myToken = $token->getToken();
		$client = new Stevenmaguire\Uber\Client(array(
			'access_token' => $myToken,
			'server_token' => 'cxt-44SCSG5gjGROKHGHfd8-eY8KiHgFrDZv_TC0cJJ',
			'use_sandbox'  => true, // optional, default false
			'version'      => 'v1.2', // optional, default 'v1.2'
			'locale'       => 'en_US', // optional, default 'en_US'
		));
		
		$client->setVersion('v1.2'); // or v1.1
		$history = $client->getHistory(array(
			'limit' => 50, // optional
			'offset' => 0 // optional
		));
		print_r($history);
```

Thanks!!

**Comment by stevenmaguire** [comment]
I am not sure. You should report this issue to the Uber if you're receiving Internal Server Error. Also, read the documentation about history. https://developer.uber.com/docs/riders/references/api/v1.2/history-get

**Comment by neutronixx** [comment]
Every thin works if I use curl php and **server token**  instead of Bearer


```
$url = 'https://api.uber.com/v1.2/products?latitude=37.7752315&longitude=-122.418075';
		
		$ch = curl_init();
		curl_setopt_array($ch, array(
			CURLOPT_URL => $url,
			CURLOPT_HEADER => false,
			CURLOPT_FOLLOWLOCATION => true,
			CURLOPT_SSL_VERIFYPEER => false,
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_USERAGENT => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.16 (KHTML, like Gecko) \ Chrome/24.0.1304.0 Safari/537.16', 
			CURLOPT_CONNECTTIMEOUT => 180,
			CURLOPT_TIMEOUT => 180 + 60,
			CURLOPT_COOKIE => 'lang=en;'
		));
		
		$headers = [
			'Authorization: Token cxt-HbCRGhJkIuYtR5Y7CC08-eY8LOIhgv_T7HcJ',
			'Accept-Language: en_US',
			'Content-Type: application/json'
		];
		
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		
		$productsJson = curl_exec($ch);

```


Is there something to modify in your library?


Thanks

**Comment by neutronixx** [comment]
For some reason  $myToken = $token->getToken(); comes truncated, this is the problem, I performed all steps using just curl and it worked fine, the token from curl is larger than $myToken.

any idea to fix it in you library?

**Comment by stevenmaguire** [comment]
What does it look like when you set `$myToken = (string) $token;`?

Also, how is `$token` being created?

**Comment by neutronixx** [comment]
This is the code:


```
$provider = new Stevenmaguire\OAuth2\Client\Provider\Uber([
	'clientId'          => 'kFvg123123Zu5OJ',
	'clientSecret'      => 'xg123456123123Brb',
	'redirectUri'       => 'https://mysite.com/tests-uber.php'
]);

if (!isset($_GET['code'])) {

	// If we don't have an authorization code then get one
	$options = [
		'state' => 'OPTIONAL_CUSTOM_CONFIGURED_STATE',
		'scope' => ['profile','history_lite','history','request','request_receipt','places','ride_widgets','all_trips'] // array or string
	];
	$authUrl = $provider->getAuthorizationUrl($options);
	$_SESSION['oauth2state'] = $provider->getState();
	header('Location: '.$authUrl);
	exit;

// Check given state against previously stored one to mitigate CSRF attack
} elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {

	unset($_SESSION['oauth2state']);
	exit('Invalid state');

} else {
	
	// Try to get an access token (using the authorization code grant)
	$token = $provider->getAccessToken('authorization_code', [
		'code' => $_GET['code']
	]);
       $myToken = $token->getToken();
}
```




And it looks like this:

> print_r($token);
> 
> League\OAuth2\Client\Token\AccessToken Object ( [accessToken:protected] => 4ZvJJsHvJecX69MDscaDwu9CaINZg5 [expires:protected] => 1488062756 [refreshToken:protected] => 9Rp08joPM86TdCCqDU4odOSFZVIF6h [resourceOwnerId:protected] => [values:protected] => Array ( [last_authenticated] => 1485380669 [token_type] => Bearer [scope] => profile history_lite history request request_receipt places ride_widgets all_trips ) ) 
> 
> myToken: 4ZvJJsHvJecX69MDscaDwu9CaINZg5
> 


Thanks!!

**Comment by stevenmaguire** [comment]
This looks correct to me, no truncation. Whats the problem?

```
print_r($token);

League\OAuth2\Client\Token\AccessToken Object ( [accessToken:protected] => 4ZvJJsHvJecX69MDscaDwu9CaINZg5 [expires:protected] => 1488062756 [refreshToken:protected] => 9Rp08joPM86TdCCqDU4odOSFZVIF6h [resourceOwnerId:protected] => [values:protected] => Array ( [last_authenticated] => 1485380669 [token_type] => Bearer [scope] => profile history_lite history request request_receipt places ride_widgets all_trips ) )

myToken: 4ZvJJsHvJecX69MDscaDwu9CaINZg5
```

**Comment by neutronixx** [comment]
If I replace $myToken by a token from CLI OAuth with curl :  

> eyJhbJciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wSXMiOlsicHJvSmlsSSIsImhpc3RvcnlfbJl0SSIsImhpc3RvcnkiLCJySXF1SXN0IiwicmVxdWVzdF9ySWNlaXV0IiwicJxhY2VzIiwicmlkSV93aWRnSXRzIiwiYWxsX3RyaXVzIl0sInN1YiI6IjA1SjliYTVhLWUxYmMtNDIzYS1iOJQ3LTRhSTViYWSjNTAzYSIsImlzcyI6InViSXItdXMxIiwianRpIjoiMJM5STJjMzYtOJM3Ny00MDM3LTk1MzktMzIxOTD0OTUySmRmIiwiSXhwIjoxNDg4MDYyNjk5LCJpYXQiOjD0ODU0NzA2OTksInVhY3QiOiJFV3FSajVCQVloM2tNc1V0SDFtVkpKVFpvdFQ0NnciLCJuYmYiOjD0ODU0NzA2MDksImF1SCI6ImtJdjV3T1VQOWN5UV8taC1faJFJYlI0cHhqSFp1NU9KIn0.X5JDc89dzs6HTO4VsFO3g0lATkO-Ym5xk7myJD8o_PjnI_FDv8tgCAr-qJvh1YgxCm7X5w-cl-RlzNsAnKKFx0KPV-7onQSF1ub6h0pme-tHqpSVDTTC1a7O8JvvszR5giCr-YOujwJ1qVCclXNu9UANrx5mtwJU9mqeNryiFMVt2MjiPNsz5c2RmkkkYlbDJyyObAo1yrx3C_MgHuO0Hg_4_rlfV7kK7kuprbdOaO0N-i2-NfbV1Xa4Si8epQ0Q3V07Ho8dcK0SS1fyvpH_s_mgbC7Mjfz-euNXdVMcJ_rFaHcSs2JTMlylKxDbcN7FSvFviJqu1wXS5Clj8PJVbQ




All works.
