### ISSUE TITLE
Update Ride Request getting error  -  Method Not Allowed (405)

### ISSUE THREAD

**Issue by hari-web** [stevenmaguire/uber-php#19]
This is my update ride code:
```

 $client 			= new Client($this->getDefaultUberConfig ($userAccessToken->access_token));
    $updateRequest = [
				'end_latitude' 	=> $newDestinationLat,
				'end_longitude' => $newDestinationLng,

			];
    $updateRequest 	= $client->setRequest($requestId, $updateRequest);

```

But I'm gettting this error: Method not supported for this endpoint (405). It seems we need to make HTTP method PATCH here. (reference: https://developer.uber.com/docs/riders/references/api/v1.2/requests-request_id-patch)
How to call this API using PATCH method?

Thanks,

**Comment by stevenmaguire** [comment]
Great catch @phpnets! Thank you. I've updated the code and cut a new patch release.

https://github.com/stevenmaguire/uber-php/releases/tag/1.5.1

Please try it out and let me know if it resolves your issue.

**Comment by hari-web** [comment]
@stevenmaguire  Yeah its worked. Thank you
