### ISSUE TITLE
Add support for Driver APIs

### ISSUE THREAD

**Issue by dustinwhittle** [stevenmaguire/uber-php#20]
Can you add support for the Uber Driver APIs? Here is an [example diff from the python sdk](https://github.com/uber/rides-python-sdk/pull/45/files#diff-f28d240a7be85035693dfe494cc123c6).

**Comment by stevenmaguire** [comment]
I cut a new tag with support for the three driver endpoints in the driver documentation. 

https://github.com/stevenmaguire/uber-php/releases/tag/1.6.0

Please let me know if something needs a closer eye.
