### ISSUE TITLE
Driver Get Trip

### ISSUE THREAD

**Issue by BardoBravo** [stevenmaguire/uber-php#23]
Hello,

Is it possible to retrieve the trip currently being done by the driver, or only the ones already finished?

Hugs

**Comment by stevenmaguire** [comment]
@BardoBravo have you consulted the Uber API documentation? Does the API offer this functionality?

**Comment by BardoBravo** [comment]
I am not sure. It just states it get the trip history, without specification on whether it can be the trip being executed.
Let's say the there is a request for the driver and he/she is accept it, and is going take the passenger. Will this trip be retrieved during the GET Trip API call?

**Comment by stevenmaguire** [comment]
@BardoBravo I am unsure. You might pose this question to Uber directly. This package is a wrapper for their API, and I do not work for Uber so I am unsure about that specific business logic question.

**Comment by BardoBravo** [comment]
Great. Thanks for the answers.
