### ISSUE TITLE
Does not work with your oAuth Client for Uber Guzzle Error

### ISSUE THREAD

**Issue by ubergeekzone** [stevenmaguire/uber-php#9]
Problem 1
    - Installation request for stevenmaguire/uber-php ^1.0 -> satisfiable by stevenmaguire/uber-php[1.0.0].
    - Conclusion: remove guzzlehttp/guzzle 6.1.1
    - Conclusion: don't install guzzlehttp/guzzle 6.1.1
    - stevenmaguire/uber-php 1.0.0 requires guzzlehttp/guzzle ~5.2 -> satisfiable by guzzlehttp/guzzle[5.2.0, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.1.1].
    - Installation request for guzzlehttp/guzzle == 6.1.1.0 -> satisfiable by guzzlehttp/guzzle[6.1.1].

**Comment by bkrajendra** [comment]
Hi @ubergeekzone I also got stuck with same issue.
Its due to requirement of v 1.0.0. 
Using following option might work for u.

```
promt>composer require stevenmaguire/uber-php:dev-master
```

**Comment by stevenmaguire** [comment]
Try to install and use the latest version, [1.4.0](https://github.com/stevenmaguire/uber-php/releases/tag/1.4.0).
